#Ansible server: 192.168.1.131
#Need to pre-config the switches
---
- name: Deploying service testing script
  hosts: deployerserver
  gather_facts: no
  connection: local
  vars:
    ips_param: "{{ ips }}"
    script_param: "{{ script }}"
    services_param: "{{ services }}"
  tasks:
    - debug:
          msg: "{{ script_param }} --ips {{ ips_param }} --services {{ services_param }}"
    #- name: Running the base testcases for the network
    #  script: "{{ script_param }} --ips {{ ips_param }} --services {{ services_param }}"
    #  args:
    #      executable: python3

    #- debug:
    #    msg: "{{ script_param }} --ips {{ ips_param }}"
