#Ansible server: 192.168.1.131
#Need to pre-config the switches
---
- name: Installing apache and FTP on Office 1 and Office 3 VM's
  hosts: 192.168.13.10
  become: yes
  gather_facts: yes
  connection: local
  tasks:
  - name: updating the apt cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

#  - name: Wait until apt lock file is removed
#  wait_for:
#    path: /var/lock/file.lock
#    state: absent

  - name: Install apache2 & FTP
    apt: 
      pkg:
      - vsftpd
      - apache2
      update_cache: yes 
      state: latest
      install_recommends: yes

  - name: Adding Firewall rules
    command: "{{ item }}"
    with_items:
      - /usr/sbin/ufw allow OpenSSH
      - /usr/sbin/ufw allow 21/tcp
      - /usr/sbin/ufw allow 80/tcp
      - /usr/sbin/ufw allow 40000:50000/tcp
      - /usr/sbin/ufw allow 990/tcp
      - /usr/sbin/ufw enable
    ignore_errors: yes

  - name: Adding a FTP user
    user:
      name: ftpuser
      shell: /bin/bash
      password: 'ftpuser'
      home: /var/www/
    ignore_errors: no

  - name: Changing the file permissions for the ftp dir
    file:
      path: /var/www/html
      owner: ftpuser
      group: ftpuser
      mode: '0744'

  - name: Restarting the ansible service
    service:
      name: vsftpd
      state: restarted

  - name: Allowing writing in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#write_enable=YES" line="write_enable=YES"

  - name: Allowing chroot in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#chroot_local_user=YES" line="chroot_local_user=YES"

  - name: Allowing correct permissions in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#local_umask=022" line="local_umask=022"

  - name: Allowing force dot files in ftp
    lineinfile: dest=/etc/vsftpd.conf line="force_dot_files=YES"

  - name: Allowing port 40000
    lineinfile: dest=/etc/vsftpd.conf line="pasv_min_port=40000"

  - name: Allowing port 50000
    lineinfile: dest=/etc/vsftpd.conf line="pasv_max_port=50000"

  - name: Restarting FTP service
    command: systemctl restart vsftpd
