DOCUMENTATION = '''
---
module: deploy_servies
short_description: This module deploys the services for the VMs within the azure network so service testing can take place.
'''
---
- name: Installing apache and FTP on Office 1 and Office 3 VMs
  hosts: OfficeVm1:OfficeVm3 
  become: yes
  gather_facts: yes
  vars:
    password: ftpuser
  tasks:
  #- name: updating the apt cache
  #  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Install FTP
    apt:
      name: vsftpd
      update_cache: yes 
      state: present
      install_recommends: yes

  - name: install nginx
    #become: true
    apt:
      name: nginx
      update_cache: yes
      state: present
      install_recommends: yes

  - name: Allowing SSH
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allowing tcp 21
    ufw:
      rule: allow
      port: 21
      proto: tcp

  - name: Allowing tcp 80
    ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: Allowing tcp 80
    ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: Allowing tcp 40000
    ufw:
      rule: allow
      port: 40000
      proto: tcp

  - name: Allowing tcp 50000
    ufw:
      rule: allow
      port: 50000
      proto: tcp

  - name: Allowing tcp 990
    ufw:
      rule: allow
      port: 990
      proto: tcp
  - name: enabling ufw
    ufw:
      state: enabled

  - name: Create directory
    file:
      path: /var/ftp/public
      state: directory

  - name: Adding a FTP user
    user:
      name: ftpuser
      password: "{{ password | password_hash("sha512") }}"
      home: /var/ftp/public

  - name: Changing the file permissions for the ftp dir
    file:
      path: /var/ftp/public
      owner: ftpuser
      group: ftpuser
      mode: "0744"

  - name: Restarting the ansible service
    service:
      name: vsftpd
      state: reloaded

  - name: Allowing writing in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#write_enable=YES" line="write_enable=YES"

  - name: Allowing writable chroot
    lineinfile: dest=/etc/vsftpd.conf line="allow_writeable_chroot=YES"

  - name: Allowing chroot in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#chroot_local_user=YES" line="chroot_local_user=YES"

  - name: Allowing correct permissions in the ftp conf
    lineinfile: dest=/etc/vsftpd.conf regexp="^#local_umask=022" line="local_umask=022"

  - name: Allowing force dot files in ftp
    lineinfile: dest=/etc/vsftpd.conf line="force_dot_files=YES"

  - name: Allowing port 40000
    lineinfile: dest=/etc/vsftpd.conf line="pasv_min_port=40000"

  - name: Allowing port 50000
    lineinfile: dest=/etc/vsftpd.conf line="pasv_max_port=50000"

  - name: Restarting FTP service
    command: systemctl restart vsftpd

