#Ansible server: 192.168.1.131
#Need to pre-config the switches
---
- name: Deploying base scripts to remote nodes
  hosts: deployerserver
  gather_facts: no
  connection: local
  vars:
    ips_param: "{{ ips }}"
    script_param: "{{ script }}"
  tasks:
    - name: Running the base testcases for the network
      script: "{{ script_param }} --ips {{ ips_param }}"
      args:
          executable: python3

    #- debug:
    #    msg: "{{ script_param }} --ips {{ ips_param }}"



