#Ansible server: 192.168.1.131
#Need to pre-config the switches
---
- name: configurating the cisco devices
  hosts: R1
  gather_facts: no
  connection: local
  tasks:
  #wait for the cisco nodes to switch on.
  - pause:
      seconds : 10
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        This is a login in Banner made by ansible for R1
      provider:
        auth_pass: Cisco
        authorize: yes
        username: Cisco
        password: Cisco
        host: 192.168.12.1

- hosts: R2
  gather_facts: no
  connection: local
  tasks:
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        This is a login in Banner made by ansible for R2
      provider:
        auth_pass: Cisco
        authorize: yes
        username: Cisco
        password: Cisco
        host: 192.168.12.2

- hosts: R3
  gather_facts: no
  connection: local
  tasks:
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        This is a login in Banner made by ansible for R3
      provider:
        auth_pass: Cisco
        authorize: yes
        username: Cisco
        password: Cisco
        host: 192.168.12.3