#Ansible server: 192.168.59.128
#Need to pre-config the switches
- name: Deployment of mini-Lan network 1
  gather_facts: False
  hosts: R1
  tasks:
    - name: Send config to R1
      ios_config:
        lines:
          - ip address 192.168.10.1 255.255.255.0
          - no shut
        parents: interface GigabitEthernet 0/0


  hosts: R1
  tasks:
    - name: Setting interfaces for R1



  hosts: R2
  tasks:
    - name: Setting interfaces for R2
